import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home({ todo }) {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Tangem web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Tangem
        </h1>
        <div className={styles.center}>
          <p>Todo:</p>
          <p>{todo.id}</p>
          <p>{todo.title}</p>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>Footer</p>
      </footer>
    </div>
  )
}

// SSG for testing purposes
export async function getStaticProps(context) {
  const response = await fetch('https://jsonplaceholder.typicode.com/todos/1')
  const todo = await response.json()

  return {
    props: {
      todo,
    },
  }
}
